# -*- coding: utf-8 -*-
"""Car Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ud_bu85--XpqR69lAeXXp_bNOHuWICyx
"""

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('car_data.csv',encoding='latin-1')

make_data = df['Make'].value_counts()

make_data.plot(kind='pie',autopct='%1.1f%%',title='Car Brands',legend=False)

"""The most popular car brand is Ford because the make is a biggest car brand to audiences. The second biggest car brand is Toyota and the third biggest car brand is Volkswagen. Other car brands has the least popular frequencies than biggest car brands."""

model_data = df['Model'].value_counts()

model_data.plot(kind='pie',autopct='%1.1f%%',title='Car Models',legend=False)

"""The biggest car model is Fiesta because this car model from Ford is a most popular model to audiences. The second biggest car model is Yaris and the third biggest car model is T Cross. Other car models has the same frequencies."""

color_data = df['Colour'].value_counts()

color_data.plot(kind='pie',autopct='%1.1f%%',title='Car Colours',legend=False)

"""The most popular colour is White and these other car colours has the same frequencies."""

fuel_data = df['Fuel Type'].value_counts()

fuel_data.plot(kind='pie',autopct='%1.1f%%',title='Car Fuel Types',legend=True)

"""All the cars are Unleaded Fuel type than Diesel and Electric."""

transmission_data = df['Transmission'].value_counts()

transmission_data.plot(kind='pie',autopct='%1.1f%%',title='Car Transmissions',legend=True)

"""The biggest transmission is Manual because most of the cars are manual for the audiences and the second biggest is Automatic because audiences interested in automatic cars than manual."""
