# -*- coding: utf-8 -*-
"""Theory test project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-JTJ8dC45wwu5hgiMrQiHAN9u5UvsU2
"""

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('theory_test_data.csv',encoding='latin-1')

grade_data = df['Status'].value_counts()

grade_data.plot(kind='pie',legend=True,autopct='%1.1f%%',title='Theory Test Results')

grade_data.plot(kind='bar',color='rebeccapurple',ylabel='Frequency',xlabel='Grade',title='Theory Test Results')

"""Most of the students has passed their driving theory test and some of the students failed their test."""